/* lv2.c -- Dynamo 0C EQ : LV2 wrapper for the DSP core.
 *
 * Per-channel chain (L/R): optional DRIVE -> HP -> 4 bells (LOW/HI switch bell<->shelf) -> LP. Each
 * EQ section is an analog-matched design of the analog prototype (dsp.h / autogenerated coeffs.h),
 * run at the base rate (no oversampling). Only the non-linear drive is (optionally) oversampled.
 * Control + audio ports only: no worker, no atoms, no file state.
 */
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include <lv2/core/lv2.h>

#if defined(__SSE__)
#include <xmmintrin.h>
#endif
#if defined(__SSE3__)
#include <pmmintrin.h>
#endif

#include "uris.h"
#include "ports.h"
#include "dsp.h"

/* flush-to-zero + denormals-are-zero: avoids CPU spikes from denormals in the IIRs during silence */
static inline void denormal_off(void) {
#if defined(__SSE__)
  _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
#endif
#if defined(__SSE3__)
  _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
#endif
}

#define ZC_MAXBLK 1024     /* we process in chunks of <= 1024 samples (bounded scratch) */

typedef struct {
  float *port[ZC_N_PORTS];          /* pointers to port buffers, by index */
  double base_fs;

  ZcChain chL, chR;                 /* CURRENT chain, per channel */
  ZcChain chL_p, chR_p;             /* PREVIOUS chain (fades out during the crossfade) */
  /* ping-pong scratch for the DRIVE oversampling: max factor is 4x, so a 1024-sample block needs
   * 4096 doubles; *8 keeps a 2x safety margin. (The EQ chain runs at 1x and needs no scratch.) */
  double sa[ZC_MAXBLK * 8];
  double sb[ZC_MAXBLK * 8];

  ZcDriveOS drvL, drvR;             /* CURRENT drive (input stage, before the EQ; optional OS) */
  ZcDriveOS drvL_p, drvR_p;         /* PREVIOUS drive */
  float  pbufL[ZC_MAXBLK], pbufR[ZC_MAXBLK];   /* previous path's output, for mixing */

  int   cur_bypass, cur_drive_on, cur_drive_os;   /* config of the CURRENT path */
  int   prev_bypass, prev_drive_on;               /* config of the PREVIOUS path (during the fade) */
  int   xfade;                      /* crossfade samples remaining (0 = no transition) */
  int   cfg;                        /* config token; a change triggers the crossfade */

  int   last_sig;                   /* structure signature, to detect rebuild */
  int   have;                       /* 0 until the first build */
  float latency_samples;
  ZcControls cur_ct;                /* controls the CURRENT chain was (re)built/refreshed with:
                                     * lets us skip the per-block coeff refresh when nothing moved */
} Zc;

#define ZC_XFADE   256          /* declick crossfade samples (~5.3 ms @48k) */
#define ZC_CFG_BYPASS 0x40000000 /* config token when POWER is off (sig never reaches it) */
#define ZC_CFG_DRIVE  0x01000000 /* token bit: drive active */
#define ZC_CFG_DRVOS_SHIFT 20    /* token field (2 bits): drive-OS selector 0/1/2 (Off/2x/4x) */

/* processes a full path (optional drive -> EQ chain) in place. bypass = dry copy.
 * The drive (with its optional oversampling) writes into 'out' using the sa/sb scratch; the EQ chain
 * then runs in place at the base rate (no scratch). */
static inline void process_path(int bypass, ZcDriveOS *dv, int drive_on, ZcChain *ch,
                                const float *in, float *out, int m, double *sa, double *sb) {
  if (bypass) { if (out != in) memmove(out, in, m * sizeof(float)); return; }
  if (drive_on) { zc_driveos_process(dv, in, out, m, sa, sb);
                  zc_chain_process(ch, out, out, m); }
  else          zc_chain_process(ch, in, out, m);
}

/* --- structure signature: which sections/kinds exist (rebuild only if it changes) --- */
static int structure_sig(const ZcControls *ct) {
  return (ct->hp_on ? 1 : 0)
       | (ct->lp_on ? 2 : 0)
       | (ct->band[0].shelf ? 4 : 0)
       | (ct->band[3].shelf ? 8 : 0)
       | (ct->lp_resonant ? 16 : 0)
       | (ct->band[0].on ? 32 : 0)            /* EQ engage: bands in/out = structure change */
       | (ct->hp_bump ? 64 : 0);              /* BUMP changes the HP's Q */
}

static int os_factor(float port_val) {
  int v = (int)(port_val + 0.5f);
  return v <= 0 ? 1 : (v == 1 ? 2 : 4);
}

static void read_controls(Zc *self, ZcControls *ct) {
  memset(ct, 0, sizeof *ct);
  /* HP/LP: the filter engages by knob POSITION (off at the extreme):
     HP off at the full-CCW end (norm 0), LP off at the full-CW end (norm 1). The *_ON port is an
     extra optional enable (default 1), in case a host wants to disable it. */
  ct->hp_freq = *self->port[P_HP_FREQ];
  ct->hp_on = (*self->port[P_HP_ON] > 0.5f) && (ct->hp_freq > 0.0005f);
  ct->hp_bump = *self->port[P_HP_BUMP] > 0.5f;
  ct->lp_freq = *self->port[P_LP_FREQ];
  ct->lp_on = (*self->port[P_LP_ON] > 0.5f) && (ct->lp_freq < 0.9995f);
  ct->lp_resonant = *self->port[P_LP_MODE] > 0.5f;
  /* bands: 0=low 1=lomid 2=himid 3=hi. EQ engage (P_EQ_ON) activates them all at once;
     HP/LP don't depend on it. Flat (gain 0.5) = transparent. */
  int eq_on = *self->port[P_EQ_ON] > 0.5f;
  ct->band[0].on = eq_on; ct->band[0].shelf = *self->port[P_LF_SHELF] > 0.5f;
  ct->band[0].freq = *self->port[P_LO_FREQ];    ct->band[0].gain = *self->port[P_LO_GAIN];
  ct->band[1].on = eq_on; ct->band[1].freq = *self->port[P_LOMID_FREQ]; ct->band[1].gain = *self->port[P_LOMID_GAIN];
  ct->band[2].on = eq_on; ct->band[2].freq = *self->port[P_HIMID_FREQ]; ct->band[2].gain = *self->port[P_HIMID_GAIN];
  ct->band[3].on = eq_on; ct->band[3].shelf = *self->port[P_HF_SHELF] > 0.5f;
  ct->band[3].freq = *self->port[P_HI_FREQ];    ct->band[3].gain = *self->port[P_HI_GAIN];
}

static LV2_Handle
instantiate(const LV2_Descriptor *d, double rate, const char *bundle,
            const LV2_Feature *const *features)
{
  (void)d; (void)bundle; (void)features;
  Zc *self = (Zc *)calloc(1, sizeof(Zc));
  if (!self) return NULL;
  self->base_fs = rate;
  self->have = 0;
  self->last_sig = -1;
  return (LV2_Handle)self;
}

static void connect_port(LV2_Handle instance, uint32_t port, void *data) {
  Zc *self = (Zc *)instance;
  if (port < ZC_N_PORTS) self->port[port] = (float *)data;
}

static void activate(LV2_Handle instance) {
  Zc *self = (Zc *)instance;
  zc_chain_reset_state(&self->chL);
  zc_chain_reset_state(&self->chR);
  zc_driveos_reset(&self->drvL); zc_driveos_reset(&self->drvR);
  self->xfade = 0;          /* no transition pending */
  self->cfg = -1;           /* force (re)config on the first run, without triggering a crossfade */
  self->have = 0;
}

static void run(LV2_Handle instance, uint32_t n_samples) {
  Zc *self = (Zc *)instance;
  denormal_off();
  const float *inL = self->port[P_IN_L], *inR = self->port[P_IN_R];
  float *outL = self->port[P_OUT_L], *outR = self->port[P_OUT_R];

  const int power = *self->port[P_POWER] > 0.5f;

  /* --- configure the CURRENT path (chL/chR + drive) and decide the config token --- */
  ZcControls ct; read_controls(self, &ct);
  int sig = 0, drive_on = 0, drive_os_sel = 0, drive_os = 1;
  double drive_knob = 0.0;
  if (power) {
    sig = structure_sig(&ct);
    drive_knob = self->port[P_DRIVE] ? (double)*self->port[P_DRIVE] : 0.0;
    drive_on = drive_knob > 1e-4;
    if (drive_on && self->port[P_DRIVE_OS]) {          /* 1x/2x/4x, only meaningful when drive is on */
      drive_os_sel = (int)(*self->port[P_DRIVE_OS] + 0.5f);
      if (drive_os_sel < 0) drive_os_sel = 0; else if (drive_os_sel > 2) drive_os_sel = 2;
      drive_os = os_factor((float)drive_os_sel);       /* 0->1x 1->2x 2->4x */
    }
  }

  /* Config token: POWER off, structure, and drive on/off + its OS factor. A CHANGE here triggers a
   * declick crossfade (the old path fades out as the new one comes in), so that toggling
   * POWER / EQ / filters / shelf / bump / drive produces no audible step. Moving continuous knobs
   * (EQ freq/gain, drive intensity) does NOT change the token -> hot refresh, no fade. */
  int newcfg = power ? (sig | (drive_on ? (ZC_CFG_DRIVE | (drive_os_sel << ZC_CFG_DRVOS_SHIFT)) : 0))
                     : ZC_CFG_BYPASS;

  /* A config change triggers a declick crossfade. While one is still running, DEFER the new config
   * (don't mutate the live path mid-fade): transitions serialize, so rapid toggles never click.
   * The deferred config is picked up on the block after the current fade ends. */
  int changed = self->have && newcfg != self->cfg;
  int defer   = changed && self->xfade > 0;

  if (changed && self->xfade == 0) {
    /* snapshot the current path -> previous; start the crossfade */
    self->chL_p = self->chL; self->chR_p = self->chR;
    self->drvL_p = self->drvL; self->drvR_p = self->drvR;
    self->prev_bypass = self->cur_bypass; self->prev_drive_on = self->cur_drive_on;
    self->xfade = ZC_XFADE;
  }

  /* apply the new config to the current path (skipped while a fade is deferring it) */
  if (!defer) {
    if (power) {
      if (!self->have || sig != self->last_sig) {  /* structure -> rebuild (state zeroed) */
        zc_chain_build(&self->chL, &ct, self->base_fs);
        zc_chain_build(&self->chR, &ct, self->base_fs);
        self->last_sig = sig;
        self->cur_ct = ct;
      } else if (memcmp(&ct, &self->cur_ct, sizeof ct) != 0) {  /* continuous knobs moved -> hot refresh */
        zc_chain_update(&self->chL, &ct);                       /* skipped when ct is unchanged: zc_chain_fill is a */
        zc_chain_update(&self->chR, &ct);                       /* pure fn of (ct, fs), so it would recompute the */
        self->cur_ct = ct;                                      /* SAME coeffs -> skipping is bit-identical */
      }
      if (drive_on) {
        /* fresh drive state on engage OR when the OS factor changed (a token change already forced a
         * declick crossfade); otherwise just hot-refresh the gain (continuous knob move, no click). */
        zc_driveos_set(&self->drvL, drive_knob, self->base_fs, drive_os);
        zc_driveos_set(&self->drvR, drive_knob, self->base_fs, drive_os);
        if (!self->cur_drive_on || drive_os != self->cur_drive_os) {
          zc_driveos_reset(&self->drvL); zc_driveos_reset(&self->drvR);
        }
      }
    }
    self->cur_bypass = !power; self->cur_drive_on = drive_on; self->cur_drive_os = drive_os;
    self->have = 1; self->cfg = newcfg;
    /* latency: only the DRIVE oversampling adds any (its FIR round-trip), and only while engaged.
     * The EQ is analog-matched at the base rate -> zero latency. */
    self->latency_samples = (power && drive_on && drive_os > 1) ? zc_driveos_latency(drive_os) : 0.0f;
  }
  if (self->port[P_LATENCY]) *self->port[P_LATENCY] = power ? self->latency_samples : 0.0f;

  /* --- block processing: current path; if crossfading, the previous one too, then mixed --- */
  for (uint32_t off = 0; off < n_samples; off += ZC_MAXBLK) {
    int m = (int)((off + ZC_MAXBLK <= n_samples) ? ZC_MAXBLK : (n_samples - off));
    const float *xl = inL + off, *xr = inR + off;
    float *yl = outL + off, *yr = outR + off;

    process_path(self->cur_bypass, &self->drvL, self->cur_drive_on, &self->chL, xl, yl, m, self->sa, self->sb);
    process_path(self->cur_bypass, &self->drvR, self->cur_drive_on, &self->chR, xr, yr, m, self->sa, self->sb);

    if (self->xfade > 0) {
      process_path(self->prev_bypass, &self->drvL_p, self->prev_drive_on, &self->chL_p, xl, self->pbufL, m, self->sa, self->sb);
      process_path(self->prev_bypass, &self->drvR_p, self->prev_drive_on, &self->chR_p, xr, self->pbufR, m, self->sa, self->sb);
      int xf = self->xfade;
      for (int i = 0; i < m; i++) {
        double t = 1.0 - (double)xf / ZC_XFADE;      /* 0 -> 1: weight of the new path */
        yl[i] = (float)(self->pbufL[i] * (1.0 - t) + yl[i] * t);
        yr[i] = (float)(self->pbufR[i] * (1.0 - t) + yr[i] * t);
        if (xf > 0) xf--;
      }
      self->xfade = xf;
    }
  }
}

static void cleanup(LV2_Handle instance) { free(instance); }

static const LV2_Descriptor descriptor = {
  ZC_URI, instantiate, connect_port, activate, run, NULL /*deactivate*/, cleanup, NULL /*extension_data*/
};

LV2_SYMBOL_EXPORT const LV2_Descriptor *lv2_descriptor(uint32_t index) {
  return index == 0 ? &descriptor : NULL;
}
