/* lv2.c -- Dynamo 0C EQ : LV2 wrapper for the DSP core.
 *
 * Per-channel chain (L/R): HP -> 4 bells (LOW/HI switch bell<->shelf) -> LP, each section
 * realized by oversampled bilinear of the analog prototype (dsp.h / autogenerated coeffs.h).
 * Control + audio ports only: no worker, no atoms, no file state.
 */
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include <lv2/core/lv2.h>

#if defined(__SSE__)
#include <xmmintrin.h>
#endif
#if defined(__SSE3__)
#include <pmmintrin.h>
#endif

#include "uris.h"
#include "ports.h"
#include "dsp.h"

/* flush-to-zero + denormals-are-zero: avoids CPU spikes from denormals in the IIRs during silence */
static inline void denormal_off(void) {
#if defined(__SSE__)
  _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
#endif
#if defined(__SSE3__)
  _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
#endif
}

#define ZC_MAXBLK 1024     /* we process in chunks of <= 1024 samples (bounded scratch) */

typedef struct {
  float *port[ZC_N_PORTS];          /* pointers to port buffers, by index */
  double base_fs;

  ZcChain chL, chR;                 /* CURRENT chain, per channel */
  ZcChain chL_p, chR_p;             /* PREVIOUS chain (fades out during the crossfade) */
  /* ping-pong scratch for oversampling: max factor is 4x, so a 1024-sample block needs 4096
   * doubles; *8 keeps a 2x safety margin (and survives a hypothetical 8x). */
  double sa[ZC_MAXBLK * 8];
  double sb[ZC_MAXBLK * 8];

  ZcDrive drvL, drvR;               /* CURRENT drive (input stage, before the EQ) */
  ZcDrive drvL_p, drvR_p;           /* PREVIOUS drive */
  float  pbufL[ZC_MAXBLK], pbufR[ZC_MAXBLK];   /* previous path's output, for mixing */

  int   cur_bypass, cur_drive_on;   /* config of the CURRENT path */
  int   prev_bypass, prev_drive_on; /* config of the PREVIOUS path (during the fade) */
  int   xfade;                      /* crossfade samples remaining (0 = no transition) */
  int   cfg;                        /* config token; a change triggers the crossfade */

  int   last_sig;                   /* structure signature, to detect rebuild */
  int   have;                       /* 0 until the first build */
  float latency_samples;

  /* Auto mode (adaptive OS): cache so we don't recompute the OS every block, only when
   * the knobs change (the computation sweeps sections x freqs and must not run for nothing).
   * auto_age throttles re-computation to ~50 ms when controls are being automated continuously. */
  ZcControls auto_ct;   int auto_os;   int auto_valid;   int auto_age;
} Zc;

#define ZC_AUTO_TARGET_DB 0.2   /* bilinear error tolerated in Auto mode (inaudible) */
#define ZC_XFADE   256          /* declick crossfade samples (~5.3 ms @48k) */
#define ZC_CFG_BYPASS 0x40000000 /* config token when POWER is off (sig never reaches it) */
#define ZC_CFG_DRIVE  0x01000000 /* token bit: drive active */

/* processes a full path (optional drive -> EQ chain) in place. bypass = dry copy. */
static inline void process_path(int bypass, ZcDrive *dv, int drive_on, ZcChain *ch,
                                const float *in, float *out, int m, double *sa, double *sb) {
  if (bypass) { if (out != in) memmove(out, in, m * sizeof(float)); return; }
  if (drive_on) { for (int i = 0; i < m; i++) out[i] = (float)zc_drive_tick(dv, in[i]);
                  zc_chain_process(ch, out, out, m, sa, sb); }      /* in-place: out doubles as scratch */
  else          zc_chain_process(ch, in, out, m, sa, sb);
}

/* --- structure signature: which sections/kinds/OS exist (rebuild only if it changes) --- */
static int structure_sig(const ZcControls *ct, int os) {
  return (ct->hp_on ? 1 : 0)
       | (ct->lp_on ? 2 : 0)
       | (ct->band[0].shelf ? 4 : 0)
       | (ct->band[3].shelf ? 8 : 0)
       | (ct->lp_resonant ? 16 : 0)
       | (ct->band[0].on ? 32 : 0)            /* EQ engage: bands in/out = structure change */
       | (ct->hp_bump ? 64 : 0)               /* BUMP changes the HP's Q */
       | (os << 7);
}

/* --- latency: oversampling round-trip (the IIRs are minimum-phase, no bulk delay).
 *     Measured with an impulse through the OS chain with no IIR sections. --- */
static float measure_latency(int os, double base_fs) {
  if (os <= 1) return 0.0f;
  ZcChain c; memset(&c, 0, sizeof c);
  c.os = os; c.stages = 0; for (int o = os; o > 1; o >>= 1) c.stages++;
  c.fs_os = base_fs * os; c.nsec = 0;     /* no IIR sections -> only up/down FIR */
  zc_chain_reset_state(&c);
  enum { N = 256 };
  float in[N], out[N]; double sa[N * 8], sb[N * 8];
  memset(in, 0, sizeof in); in[0] = 1.0f;
  zc_chain_process(&c, in, out, N, sa, sb);
  /* energy centroid of the output impulse = group delay */
  double num = 0, den = 0;
  for (int i = 0; i < N; i++) { double e = (double)out[i] * out[i]; num += i * e; den += e; }
  return den > 0 ? (float)(num / den) : 0.0f;
}

static int os_factor(float port_val) {
  int v = (int)(port_val + 0.5f);
  return v <= 0 ? 1 : (v == 1 ? 2 : 4);
}

static void read_controls(Zc *self, ZcControls *ct) {
  memset(ct, 0, sizeof *ct);
  /* HP/LP: the filter engages by knob POSITION (off at the extreme):
     HP off at the full-CCW end (norm 0), LP off at the full-CW end (norm 1). The *_ON port is an
     extra optional enable (default 1), in case a host wants to disable it. */
  ct->hp_freq = *self->port[P_HP_FREQ];
  ct->hp_on = (*self->port[P_HP_ON] > 0.5f) && (ct->hp_freq > 0.0005f);
  ct->hp_bump = *self->port[P_HP_BUMP] > 0.5f;
  ct->lp_freq = *self->port[P_LP_FREQ];
  ct->lp_on = (*self->port[P_LP_ON] > 0.5f) && (ct->lp_freq < 0.9995f);
  ct->lp_resonant = *self->port[P_LP_MODE] > 0.5f;
  /* bands: 0=low 1=lomid 2=himid 3=hi. EQ engage (P_EQ_ON) activates them all at once;
     HP/LP don't depend on it. Flat (gain 0.5) = transparent. */
  int eq_on = *self->port[P_EQ_ON] > 0.5f;
  ct->band[0].on = eq_on; ct->band[0].shelf = *self->port[P_LF_SHELF] > 0.5f;
  ct->band[0].freq = *self->port[P_LO_FREQ];    ct->band[0].gain = *self->port[P_LO_GAIN];
  ct->band[1].on = eq_on; ct->band[1].freq = *self->port[P_LOMID_FREQ]; ct->band[1].gain = *self->port[P_LOMID_GAIN];
  ct->band[2].on = eq_on; ct->band[2].freq = *self->port[P_HIMID_FREQ]; ct->band[2].gain = *self->port[P_HIMID_GAIN];
  ct->band[3].on = eq_on; ct->band[3].shelf = *self->port[P_HF_SHELF] > 0.5f;
  ct->band[3].freq = *self->port[P_HI_FREQ];    ct->band[3].gain = *self->port[P_HI_GAIN];
}

static LV2_Handle
instantiate(const LV2_Descriptor *d, double rate, const char *bundle,
            const LV2_Feature *const *features)
{
  (void)d; (void)bundle; (void)features;
  Zc *self = (Zc *)calloc(1, sizeof(Zc));
  if (!self) return NULL;
  self->base_fs = rate;
  self->have = 0;
  self->last_sig = -1;
  return (LV2_Handle)self;
}

static void connect_port(LV2_Handle instance, uint32_t port, void *data) {
  Zc *self = (Zc *)instance;
  if (port < ZC_N_PORTS) self->port[port] = (float *)data;
}

static void activate(LV2_Handle instance) {
  Zc *self = (Zc *)instance;
  zc_chain_reset_state(&self->chL);
  zc_chain_reset_state(&self->chR);
  zc_drive_reset(&self->drvL); zc_drive_reset(&self->drvR);
  self->xfade = 0;          /* no transition pending */
  self->cfg = -1;           /* force (re)config on the first run, without triggering a crossfade */
  self->have = 0;
}

static void run(LV2_Handle instance, uint32_t n_samples) {
  Zc *self = (Zc *)instance;
  denormal_off();
  const float *inL = self->port[P_IN_L], *inR = self->port[P_IN_R];
  float *outL = self->port[P_OUT_L], *outR = self->port[P_OUT_R];

  const int power = *self->port[P_POWER] > 0.5f;

  /* --- configure the CURRENT path (chL/chR + drive) and decide the config token --- */
  ZcControls ct; read_controls(self, &ct);
  int os = 1, sig = 0, drive_on = 0;
  double drive_knob = 0.0;
  if (power) {
    /* OS: 0/1/2 = fixed 1x/2x/4x ; >=3 = Auto (adaptive, inaudible target). Cached via memcmp. */
    if ((int)(*self->port[P_OVERSAMPLE] + 0.5f) >= 3) {
      /* recompute only when controls changed, and then at most every ~50 ms: under continuous
       * automation ct would differ every block and run the (costly) sweep for nothing. */
      int changed = !self->auto_valid || memcmp(&ct, &self->auto_ct, sizeof ct) != 0;
      self->auto_age += (int)n_samples;
      if (changed && (!self->auto_valid || self->auto_age >= (int)(self->base_fs * 0.05))) {
        self->auto_os = zc_chain_adaptive_os(&ct, self->base_fs, ZC_AUTO_TARGET_DB);
        self->auto_ct = ct; self->auto_valid = 1; self->auto_age = 0;
      }
      os = self->auto_os;
    } else {
      os = os_factor(*self->port[P_OVERSAMPLE]);
    }
    sig = structure_sig(&ct, os);
    drive_knob = self->port[P_DRIVE] ? (double)*self->port[P_DRIVE] : 0.0;
    drive_on = drive_knob > 1e-4;
  }

  /* Config token: POWER off, structure/OS, and drive on/off. A CHANGE here triggers a
   * declick crossfade (the old path fades out as the new one comes in), so that toggling
   * POWER / EQ / filters / shelf / bump / drive produces no audible step. Moving continuous knobs
   * (EQ freq/gain, drive intensity) does NOT change the token -> hot refresh, no fade. */
  int newcfg = power ? (sig | (drive_on ? ZC_CFG_DRIVE : 0)) : ZC_CFG_BYPASS;

  /* A config change triggers a declick crossfade. While one is still running, DEFER the new config
   * (don't mutate the live path mid-fade): transitions serialize, so rapid toggles never click.
   * The deferred config is picked up on the block after the current fade ends. */
  int changed = self->have && newcfg != self->cfg;
  int defer   = changed && self->xfade > 0;

  if (changed && self->xfade == 0) {
    /* snapshot the current path -> previous; start the crossfade */
    self->chL_p = self->chL; self->chR_p = self->chR;
    self->drvL_p = self->drvL; self->drvR_p = self->drvR;
    self->prev_bypass = self->cur_bypass; self->prev_drive_on = self->cur_drive_on;
    self->xfade = ZC_XFADE;
  }

  /* apply the new config to the current path (skipped while a fade is deferring it) */
  if (!defer) {
    if (power) {
      if (!self->have || sig != self->last_sig) {  /* structure/OS -> rebuild (state zeroed) */
        zc_chain_build(&self->chL, &ct, self->base_fs, os);
        zc_chain_build(&self->chR, &ct, self->base_fs, os);
        self->latency_samples = measure_latency(os, self->base_fs);
        self->last_sig = sig;
      } else {                                      /* continuous knobs only -> hot refresh */
        zc_chain_update(&self->chL, &ct);
        zc_chain_update(&self->chR, &ct);
      }
      if (drive_on) {
        if (!self->cur_drive_on) { zc_drive_reset(&self->drvL); zc_drive_reset(&self->drvR); }
        zc_drive_set(&self->drvL, drive_knob, self->base_fs);
        zc_drive_set(&self->drvR, drive_knob, self->base_fs);
      }
    }
    self->cur_bypass = !power; self->cur_drive_on = drive_on;
    self->have = 1; self->cfg = newcfg;
  }
  if (self->port[P_LATENCY]) *self->port[P_LATENCY] = power ? self->latency_samples : 0.0f;

  /* --- block processing: current path; if crossfading, the previous one too, then mixed --- */
  for (uint32_t off = 0; off < n_samples; off += ZC_MAXBLK) {
    int m = (int)((off + ZC_MAXBLK <= n_samples) ? ZC_MAXBLK : (n_samples - off));
    const float *xl = inL + off, *xr = inR + off;
    float *yl = outL + off, *yr = outR + off;

    process_path(self->cur_bypass, &self->drvL, self->cur_drive_on, &self->chL, xl, yl, m, self->sa, self->sb);
    process_path(self->cur_bypass, &self->drvR, self->cur_drive_on, &self->chR, xr, yr, m, self->sa, self->sb);

    if (self->xfade > 0) {
      process_path(self->prev_bypass, &self->drvL_p, self->prev_drive_on, &self->chL_p, xl, self->pbufL, m, self->sa, self->sb);
      process_path(self->prev_bypass, &self->drvR_p, self->prev_drive_on, &self->chR_p, xr, self->pbufR, m, self->sa, self->sb);
      int xf = self->xfade;
      for (int i = 0; i < m; i++) {
        double t = 1.0 - (double)xf / ZC_XFADE;      /* 0 -> 1: weight of the new path */
        yl[i] = (float)(self->pbufL[i] * (1.0 - t) + yl[i] * t);
        yr[i] = (float)(self->pbufR[i] * (1.0 - t) + yr[i] * t);
        if (xf > 0) xf--;
      }
      self->xfade = xf;
    }
  }
}

static void cleanup(LV2_Handle instance) { free(instance); }

static const LV2_Descriptor descriptor = {
  ZC_URI, instantiate, connect_port, activate, run, NULL /*deactivate*/, cleanup, NULL /*extension_data*/
};

LV2_SYMBOL_EXPORT const LV2_Descriptor *lv2_descriptor(uint32_t index) {
  return index == 0 ? &descriptor : NULL;
}
